name: Build ReCoreUI
run-name: Building ROM > ${{ inputs.device }}
on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Choose objective'
        required: true
        default: ''
      upload_cloud:
        description: 'Upload ROM to cloud (GoFile)'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Free disk space (1/4) - System Junk
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Free disk space (2/4) - Tool Cache
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: false

      - name: Free disk space (3/4)
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'

      - name: Free disk space (4/4)
        run: |
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/share/sbt
          sudo apt-get clean

      - name: Disk Space Check
        run: df -h /

      - name: Run ReCoreUI Build
        run: |
          sudo bash build.sh --build ${{ inputs.device }}


      - name: Upload ROM to Gofile
        if: inputs.upload_cloud == true
        run: |
          echo "Searching for ROM zip..."
          ROM_FILE=$(find out -type f -name "*.zip" | head -n 1)

          if [ -z "$ROM_FILE" ]; then
            echo "No ROM zip found!"
            exit 1
          fi

          echo "Found ROM: $ROM_FILE"

          SERVER=$(curl -s https://api.gofile.io/servers | jq -r '.data.servers[0].name')

          RESPONSE=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GOFILE_TOKEN }}" \
            -F "file=@$ROM_FILE" \
            -F "folderId=${{ secrets.GOFILE_FOLDER_ID }}" \
            https://$SERVER.gofile.io/uploadFile)

          echo "$RESPONSE"

          DOWNLOAD_LINK=$(echo $RESPONSE | jq -r '.data.downloadPage')

          echo "=============================="
          echo "Upload Successful!"
          echo "Download Link: $DOWNLOAD_LINK"
          echo "=============================="
